site_name: Arrietty's Website
site_url: https://arriettych.github.io

nav:
  - 主页: Home_Page.html
  - 计算机课程:
    - ADS:
      - 课程介绍: ADS.md
      - 期中考前内容: ADS_Part1.pdf
      - 期中考后内容: ADS_Part2.pdf
    - 计算机组成: 计算机组成.md
  - 金融学课程:
    - 会计学: 会计学.md
  - 关于作者: About_Me.md

theme:
  
  name: material

  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

  font: 
    text: Red Hat Text
    code: Red Hat Mono
  
  logo: assets/android-chrome-512x512.png
  favicon: assets/favicon.ico

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
      primary: white
      accent: blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/theme-light-dark
        name: Switch to system preference
      primary: black
      accent: cyan

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArriettyCh
    - icon: fontawesome/solid/at
      link: mailto:<arriettychen@zju.edu.cn>
    
copyright: Copyright &copy 2025 Arrietty's Blog