site_name: Arrietty's Universe
site_url: https://arriettych.github.io

nav:
  - 主页:
    - index.html
  - 计算机课程:
    - 计算机/index.md
    - ADS:
      - 计算机/ADS/index.md
      - Part 1: 计算机/ADS/ADS_Part1.pdf
      - Part 2: 计算机/ADS/ADS_Part2.pdf
    - 计算机组成: 
      - 计算机/计组/index.md
      - Part 1: 计算机/计组/计组_Part1.pdf
      - Part 2: 计算机/计组/计组_Part2.pdf
    - 量子计算:
      - 计算机/量子/index.md
      - 导论: 计算机/量子/导论.md
  - 金融学课程:
    - 金融/index.md
    - 计量经济学:
      - 金融/计量/index.md
      - 课程笔记: 金融/计量/计量.pdf
      - 放宽条件的模型汇总: 金融/计量/放宽条件的模型汇总.pdf
    - 量化投资:
      - 金融/量化/index.md
      - 作业一：因子复现: 金融/量化/量化_1.md
      - 作业二：研究报告: 金融/量化/量化_2.md
  - 关于我:
    - about.md
  - 友情链接:
    - link.md
        
plugins:
  - search

theme:
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    annotation: material/dots-horizontal
  
  language: zh
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - header.autohide
    - navigation.footer

  font: 
    text: Red Hat Text
    code: Red Hat Mono
  
  logo: assets/android-chrome-512x512.png
  favicon: assets/favicon.ico

  palette:

    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
      primary: white
      accent: blue

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/theme-light-dark
        name: Switch to system preference
      primary: black
      accent: cyan

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArriettyCh
    - icon: fontawesome/solid/at
      link: mailto:<arriettychen@zju.edu.cn>
    
copyright: Copyright &copy 2025 Arrietty Chen